language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - yarn flow
  - yarn lint
  - yarn test
  - yarn build
deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: build
    skip-cleanup: true
    on:
      tags: true
  - provider: npm
    email: mk@mkitt.net
    api_key: $NPM_TOKEN
    skip-cleanup: true
    on:
      tags: true
