language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - yarn flow
  - yarn lint
  - yarn test
  - yarn build
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: build
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    email: mk@mkitt.net
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
